# Generated by Django 5.0.7 on 2024-09-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zoo_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal_model",
            name="animal_type",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
